databases:
  - name: financedb
    plan: free
    databaseName: finance
    user: finance

services:
  - type: web
    plan: free
    name: finance
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn finance.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: financedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
